version: '3.3'
services:

  drone-server:
    image: drone/drone:${DRONE_VERSION}
    networks:
      backend:
    ports:
      # - 80:80
      # - 443:443
      - "${PRO_PUBLIC_IP}:8000:8000"
      # - 9000:9000
    volumes:
      - drone-data:/var/lib/drone/:rw
      # - ${SSL_PATH}:/etc/certs
    restart: always
    environment:
      - DRONE_SECRET=khs1994
      - DRONE_OPEN=true
      - DRONE_HOST=https://drone.${PRO_DOMAIN}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=7b874aab99e6cc2228c9
      - DRONE_GITHUB_SECRET=50c6cfaea5f4850db51382d46e5f5fe7d13efa6b

  drone-agent:
    image: drone/agent:${DRONE_VERSION}
    networks:
      backend:
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DRONE_HOST=https://drone.${PRO_DOMAIN}
      - DRONE_SERVER=drone-server:9000
    dns: ${DNS}

  # gogs:
  #   image: gogs/gogs
  #   networks:
  #     backend:
  #   ports:
  #     - "${SSH_PORT}:22"
  #     - "${PUBLIC_IP}:10080:3000"
  #   volumes:
  #     - gogs-data:/data:rw
  #     - ./gogs/app.prod.ini:/data/gogs/conf/app.ini:ro
  #     - ${SSL_PATH}:/data/ssl:rw
  #   extra_hosts:
  #     - "drone.${DOMAIN}:${DRONE_IP}"
  #
  # mysql:
  #   image: mysql:${MYSQL_VERSION}
  #   networks:
  #     backend:
  #   env_file: .env
  #   # ports:
  #     # - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql:rw
  #   command: ["mysqld","--character-set-server=utf8mb4"]
  #
  # registry:
  #   image: registry
  #   networks:
  #     backend:
  #   ports:
  #     - "${PUBLIC_IP}:5000:5000"
  #   volumes:
  #     - registry-data:/var/lib/registry:rw

  # nginx:
  #   image: khs1994/nginx:${NGINX_VERSION}-alpine
  #   networks:
  #     backend:
  #   env_file: .env
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d

  # webhooks:
  #   build:
  #     context: webhooks
  #   image: khs1994/ci
  #   ports:
  #     - "7777:7777"

networks:
  backend:

volumes:
  gogs-data:
  # mysql-data:
  drone-data:
  # registry-data:
