version: '3.3'
services:

  drone-server:
    image: drone/drone:${DRONE_VERSION}
    networks:
      backend:
        # ipv4_address: 172.28.1.101
    ports:
      # - 80:80
      # - 443:443
      - "${PUBLIC_IP}:8000:8000"
      # - 9000:9000
    volumes:
      - drone-data:/var/lib/drone/:rw
      # - ${SSL_PATH}:/etc/certs
    restart: always
    env_file: .env
    environment:
      - DRONE_HOST=https://drone.${DOMAIN}
      - DRONE_GOGS_URL=https://git.${DOMAIN}

  drone-agent:
    image: drone/agent:${DRONE_VERSION}
    # command: agent
    networks:
      backend:
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file: .env
    environment:
      - DRONE_HOST=https://drone.${DOMAIN}
      - DRONE_SERVER=drone-server:9000
    dns: ${DNS}

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.28.1.1/24

volumes:
  gogs-data:
  mysql-data:
  drone-data:
  registry-data:
