version: '3.4'
services:

  drone-server:
    extra_hosts:
      - "git.${DOMAIN}:${DRONE_IP}"

  drone-agent:
    extra_hosts:
      - "git.${DOMAIN}:${DRONE_IP}"

  gogs:
    image: gogs/gogs
    ports:
      - "22:22"
      - "3000:3000"
    volumes:
      - gogs-data:/data:rw
      - ./gogs/app.prod.ini:/data/gogs/conf/app.ini:ro
      - ./conf.d/ssl:/data/ssl:rw
    extra_hosts:
      - "drone.${DOMAIN}:${DRONE_IP}"

  mysql:
    image: mysql:5.7.20
    env_file: env/mysql.env
    # ports:
      # - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:rw
    command: ["mysqld","--character-set-server=utf8mb4"]

  registry:
    image: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - registry-data:/var/lib/registry:rw

  # nginx:
  #   image: khs1994/nginx:${NGINX_VERSION}-alpine
  #   networks:
  #     backend:
  #   env_file: .env
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d
